# Generated by Django 5.0.6 on 2024-06-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_productcategory_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
