# Generated by Django 5.0.6 on 2024-07-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_suplier_product_inventory_sale_producthistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='duedate',
            field=models.DateField(blank=True),
        ),
    ]
