# Generated by Django 5.0.6 on 2024-07-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_product_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='duedate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
