# Generated by Django 5.0.6 on 2024-07-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_product_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='suplier',
            name='direction',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.CharField(max_length=70),
        ),
    ]
