# Generated by Django 5.0.6 on 2024-07-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_suplier_direction_alter_product_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suplier',
            name='email',
            field=models.EmailField(blank=True, max_length=150, unique=True),
        ),
    ]
