# Generated by Django 5.0.6 on 2024-07-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_suplier_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producthistory',
            name='purchase_unit',
        ),
        migrations.AddField(
            model_name='producthistory',
            name='units_purchased',
            field=models.IntegerField(default=0),
        ),
    ]
