# Generated by Django 5.0.6 on 2024-07-10 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_producthistory_purchase_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='price',
            new_name='sales_price',
        ),
    ]
