# Generated by Django 5.0.6 on 2024-08-10 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_carouselimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigosReestablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('tiempoCreacion', models.DateTimeField()),
                ('isUtilizado', models.BooleanField(default=False)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
