# Generated by Django 5.0.6 on 2024-08-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_codigosreestablecimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
