# Generated by Django 5.0.6 on 2024-08-11 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_categoriesservice_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
