# Generated by Django 5.0.6 on 2024-08-13 09:41

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_product_url_productimage_productvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', validators=[api.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
