# Generated by Django 5.0.6 on 2024-08-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_productimage_image_alter_productimage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
