# Generated by Django 5.0.6 on 2024-08-13 23:54

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_product_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='public/product_images/', validators=[api.models.validate_image_size]),
        ),
    ]
