# Generated by Django 5.0.6 on 2024-08-14 09:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_product_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
        migrations.AddField(
            model_name='product',
            name='aud_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
