# Generated by Django 5.0.6 on 2024-08-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_product_url_product_aud_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='codigo',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
