# Generated by Django 5.0.6 on 2024-08-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_product_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='units',
            field=models.IntegerField(default=0),
        ),
    ]
