# Generated by Django 5.0.6 on 2024-08-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_carrito_itemcarrito_orden_detalleorden_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='puntuacion',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.DeleteModel(
            name='Puntuacion',
        ),
    ]
