# Generated by Django 5.0.6 on 2024-08-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_comentario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrito',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('Creando', 'Creando'), ('Enviada', 'Enviada'), ('Completada', 'Completada'), ('Eliminada', 'Eliminada')], default='Creando', max_length=10),
        ),
    ]
