# Generated by Django 5.0.6 on 2024-08-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_product_units'),
        ('api', '0027_alter_comentario_usuario'),
    ]

    operations = [
    ]
