# Generated by Django 5.0.6 on 2024-08-16 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_itemcarrito_cantidad_alter_orden_estado'),
        ('api', '0028_merge_20240815_1346'),
        ('api', '0028_merge_20240815_1548'),
    ]

    operations = [
    ]
