# Generated by Django 5.0.6 on 2024-08-18 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_itemcarrito_cantidad'),
        ('api', '0029_merge_20240816_0303'),
    ]

    operations = [
    ]
