# Generated by Django 5.0.6 on 2024-08-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_merge_20240817_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrito',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
